--COMO FAZER BACKUP DA INBOUND

--UPDATE "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND" SET
STATUS = '19/10/2023'
where left(cpudt,10) between '2022-11-01' and '2022-11-30';

SELECT count(*) FROM "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND"
where status = '19/10/2023'

--INSERT INTO "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND_BKP"
SELECT * FROM "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND"
where status = '19/10/2023'

--CONFIRMAR QUE FEZ BACKUP
SELECT COUNT(*) FROM "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND_BKP"
where status = '19/10/2023'

SELECT COUNT(*) FROM "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND"
where status ='19/10/2023'

--Não executar estes comandos abaixo
--Abaixo são comandos auxiliares e dependem da necessidade atual.
--DELETE FROM "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND"
where status = '19/10/2023'

--INSERT INTO "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND"
SELECT * FROM "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND_BKP"
where status = '19/10/2023'

--UPDATE "ASSET_TRACKING"."Y_ASSET_TRACKING_ASSET_VERSION_INBOUND" SET
STATUS = 'NotProcessed'
where left(cpudt,10) between '2022-11-01' and '2022-11-30';
